#include <fstream>
#include <random>
using namespace std;

int main()
{
    double s, f;

    std::string filename = "test_gen";
    std::ofstream ostrm(filename, std::ios::binary);
 
    
    std::random_device rd;  //Will be used to obtain a seed for the random number engine
    std::mt19937 gen(rd()); //Standard mersenne_twister_engine seeded with rd()
    std::uniform_real_distribution<> dis(-100, 0);
    std::uniform_real_distribution<> dis2(0, 100);

    s = dis(gen);
    f = dis2(gen);
    ostrm << s << " " << s << "\n" << 20000 << endl;
    for (int n = 0; n < 20000; ++n) {
        // Use dis to transform the random unsigned int generated by gen into a 
        // double in [1, 2). Each call to dis(gen) generates a new random double
	s = dis(gen);
	f = dis2(gen);
	ostrm << s << " " << s << endl;
	
    }
    
}
